edition = "2023";
package th07;

import "thdef.proto";

enum Shot {
    REIMUA = 0;
    REIMUB = 1;
    MARISAA = 2;
    MARISAB = 3;
    SAKUYAA = 4;
    SAKUYAB = 5;
}

message Th07ReplayData {
    thdef.GameId game = 1;
    uint32 version = 2;
    Shot shot = 3;
    thdef.Difficulty difficulty = 4;
    uint64 score = 5;
    string date = 6;
    string name = 7;
    float slowdown = 8;
    repeated Th07StageData stages = 100;
}

message Th07StageData {
    uint64 score = 1;
    uint32 point_items = 2;
    uint32 graze = 3;
    uint32 piv = 4;
    uint32 power = 5;
    uint32 lives = 6;
    uint32 bombs = 7;
    uint32 cherry = 8;
    uint32 cherry_max = 9;
}
